M48
; DRILL file KiCad 10.0.3-10.0.3~ubuntu24.04.1 date 2026-07-23T07:45:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-23T07:45:05+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3-10.0.3~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.350
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X44.23Y-150.475
T2
X33.0Y-57.0
X33.0Y-150.0
X63.0Y-57.0
X63.0Y-150.0
M30
